### PR TITLE
Update english.txt

### PR DESCRIPTION
**Pull request by BreakinBenny**
I've cut down on what would probably be redundant stuff such as the special units, they're special units no matter which region or faction they belong to! However, I've also given the FBI Agents and policemen unique "titles" (and being politically correct on the policewomen, sry, no harm no foul right?). There are three (four including the FBI Boss, excluding the female agents); The FBI Agent, the Veteran Agent, and the HRT unit. The Hostage Extraction Unit and all the Bulldozers sans the Halloween ones have a "_stats_name" extension, do you think something could be done with those?

### CODE REVIEW

**Comment by segabl** [comment]
There are reasons behind some of the naming, for instance for the gang members, seeing as Overkill likes to mix them randomly in newer heists, and seeing different gang names appear is a little dumb imo.
I want to have unique names as much as possible, but avoid them when it's just a different number or suffix on the unit name, like for all the FBI units, as they're not really used for that spedific role (FBI boss may be named like that but can occur multiple times in a heist, which makes little sense). Ultimately I don't want too much detail because it would be too specific.
Then, once more, there's not really a need for the tweak_ names, dunno why you insist on moving them to tweak_. They are only a fallback for when a unit name is not in the list.

**Comment by BreakinBenny** [comment]
The reason I replace the individual unit names with their tweak_id is because that's does it simpler. A Russian Taser for instance, is in no functioning way different from their American counterparts, their only difference is the apparel.

It's a simple thing to make the special enemies identified by their **tweak_id**'s, and the **_stats_name** for certain units if it exists. Black Bulldozers, Skulldozers, and Murkywater units can be identified via the latter.

**Comment by segabl** [comment]
Yes, I understand that, but it complicates the code since at the moment it just checks the unit name if that unit name is in the list and then takes the name from the localisation. if it isn't in the localisation, it doesn't take the tweak_ name instead, it just uses the unit name. so that would be code I would need to rework and quite frankly, the way it is now is at least consistent for everything apart from the swat turrets (those work with _tweak because their actual unit names are not in the list to take names from).

**Comment by BreakinBenny** [comment]
I guess I will say it again, then; my efforts were in vain, but instead of fixing up the Maximum Force Responders to print exactly that, my attempt with the tweak_id was meaningless. I will not bow down however, until my idea is right or not.

**Pull request closed without merging**
