### PR TITLE
Update NameProvider.lua

### PR DESCRIPTION
**Pull request by BreakinBenny**
Added GenSec City SWAT, Murkywater, and ZEAL.

### CODE REVIEW

**Comment by segabl** [comment]
May I ask what the point of the Murkywater gsub is? And I don't think the ZEAL actually has unique tweak data entries, unless they changed it recently.

**Comment by BreakinBenny** [comment]
I looked in the unit files for extensions, I saw the City ones and the Murkies… plus the ZEAL ones, and then I thought it'd be worth it to include those.

**Comment by segabl** [comment]
By the murky one I actually meant why you're adding a substitution that substitutes "Murkywater" with "Murkywater" which doesn't change anything. The City Swat gsub is somewhat okay, it's just a name change. ZEAL uses normal swat presets so there's not really a way to differentiate them.

**Comment by BreakinBenny** [comment]
I suppose it's because otherwise the Murkywater type will be blanked out, just an assumption on my part if the string happens to read NULL.

You don't need to include the Murkies tag if you don't want to.

**Comment by BreakinBenny** [comment]
…So, how about it? As I said, it's not a requirement to include the Murkywater one.

**Comment by segabl** [comment]
Well, like I mentioned, this change doesn't really do anything apart from renaming City SWATS to City Elite SWATS. I don't really think that it's necessary.

**Comment by BreakinBenny** [comment]
I mainly did this because I noticed the Heavy City SWAT wasn't being counted, so I thought I'd try to fix it… but it seems I've failed, then.

**Comment by segabl** [comment]
Yeah that happens because they use the same id to get their stats from so it's not really something you can fix with string substitution.

**Comment by BreakinBenny** [comment]
Then at least I tried, if that's any comfort. Thus this pull request can be closed after testing.

**Comment by segabl** [comment]
No worries, I appreciate the effort

**Comment by BreakinBenny** [comment]
I've been thinking a bit about the NameProvider and the possible enemies in PAYDAY 2; we have either riflemen or shotgunners, right? I believe that if the GenSec and ZEAL units cannot be done due to their tweak data presets, then at least it'd be possible to add a tag that lets you know if the Jokered cop is a shotgunner or rifleman.

`if _r870 then print Shotgunner`


…Then again, the shotgunner cops are rare foes unless you play Crime Spree and happen to see white-clothed heavy SWAT units and their dreaded boomsticks.

**Comment by BreakinBenny** [comment]
Looking at groupaitweakdata.lua, it seems like the generated cops could (and I mean _could_!) be detected by looking at the **self.unit_categories**

Let's see… the values **CS_swat_R870**, **CS_heavy_r870**, **FBI_swat_R870**, and **FBI_heavy_R870** are Shotgunner units for the MPD and FBI/GenSec units (and Heavy SWAT counterparts), respectively. enemies who are sorted in this unit category will be given Reinfelds, which is seemingly a requirement due to them not being special units like Bulldozers are, who in turn may use either Reinfelds, IZHMAs, or KSPs. As of this writing, HopLib still only uses **self._names**.

**Comment by segabl** [comment]
I am aware of that, but like I said, that association is only one way. There's no way I can detect what spawngroup a unit originated from or what its spawn name in groupaitweakdata is

**Comment by BreakinBenny** [comment]
Guess the only solution is to be more observant then.

**Pull request closed without merging**
